### ISSUE TITLE
Adjustments to work on Later versions of MW+on google compute cloud. 

### ISSUE THREAD

**Issue by yhacohen** [tyolab/CloudStorage#1]
Hello. 
We are trying to make this extension work on recent MedaiWiki version and to work on Compute cloud rather than on AppEngine. Right now we succeeded on replacing the app engine modules with the Google php storage client (by manually registering the gs stream wrapper), and the machine connects right to the remote bucket. We are working both on 1.25 (extension version) and 1.29 (which has a different upload architecture). 

However, the leading directories are created but the files themselves are not being uploaded to the bucket throwing some strange permission error:
```
Could not read or write file "public/1/1b/Picture1.png" due to insufficient permissions or missing directories/containers.
Could not store file "/tmp/phpiikJ8K" at "public/1/1b/Picture1.png".
```
We will be grateful for any clue or help.

**Comment by e-tang** [comment]
I think on the App Engine, Google automatically associates your account to the storage with whatever permissions you have on that bucket. If you run it on compute engine with which they don't have direct interventions, so you might have to initialize your php environment to create an association for your account with permissions to the bucket.

**Comment by yhacohen** [comment]
Thanks for the reply. The instance is already associated with the bucket (actually this is how all Google Cloud compute engine machines are configured), and also we succeeded in uploading files with php test app we've created (not through MediaWiki). 

While uploading files through the wiki all the directories are created in the machine (i.e. - "thumb/d/dd/") but the files are not created inside them. We also changed some of the file use command from "a+" to "w" (later we found out you did the same in the wiki version you used). 

Looking in the bucket logs we do see some POST requests but than the following GET gets a 404 because the files are not there.

We are trying to eliminate the issue, and thought about the following possible options:
* Problems with using lock on remote files
* Problems in using the stream wrapper.

**Comment by e-tang** [comment]
So it is hard to tell what caused the problem then. I vaguely recalled that I had the same issue before but on the App engine. I guess the only way to figure out the issue is to turn on the WikiMedia debug log, and try to catch all the Google Storage exceptions. It may be actually easier to debug on the compute engine than on  App engine.

**Comment by e-tang** [comment]
Also, you are supposed to provide a canonical destination path and not a relative path like you get on your error log, right?

Not 

```
store file "/tmp/phpiikJ8K" at "public/1/1b/Picture1.png".
```

should be:

```
store file "/tmp/phpiikJ8K" at "gs://bucket/public/1/1b/Picture1.png".
```
